import './src/fonts/myriad_pro_bold/myriad_pro_bold.css';
import './src/fonts/myriad_pro_regular/myriad_pro_regular.css';
import './src/blocks/first-container/first-container.styl';
import './src/blocks/main-info/main-info.styl';
import './src/blocks/block-header/block-header.styl';
import './src/blocks/profile/profile.styl';
import './src/blocks/contact/contact.styl';
import './src/blocks/skills/skills.styl';
import './src/blocks/second-container/second-container.styl';