import './fonts/PT Sans/pt-sans.css';
import './pages/index.styl';
import './blocks/cv-column-first/cv-column-first.styl';
import './blocks/applicant/applicant.styl';
import './blocks/cv-section-header/cv-section-header.styl';
import './blocks/profile/profile.styl';
import './blocks/contact/contact.styl';
import './blocks/skills/skills.styl';
import './blocks/cv-column-second/cv-column-second.styl';
import './blocks/education/education.styl';
import './blocks/cv-list/cv-list.styl';
import './blocks/experience/experience.styl';
import './blocks/software/software.styl';